test_dynamic_array:test_dynamic_array.o
	gcc test_dynamic_array.o -L ../ -l kael_ds -o test_dynamic_array

test_dynamic_array.o:test_dynamic_array.c
	gcc -c test_dynamic_array.c -o test_dynamic_array.o

clean:
	rm test_dynamic_array
	rm test_dynamic_array.o
